name: Nightly Build

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    env:
      FILENAME: AutoBlockIP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Archive
        run: |
          mkdir -p release
          7z a release/${{ env.FILENAME }}.zip .
        continue-on-error: true

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.FILENAME }}.zip
          path: release/${{ env.FILENAME }}.zip
      
      - name: Get current date
        id: get_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        shell: bash

      - name: Create Release
        if: ${{ success() }}
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: nightly-${{ github.run_number }}
          release_name: Nightly build ${{ github.run_number }} (${{ steps.get_date.outputs.date }})
          body: Automated nightly build for commit ${{ github.sha }}.
          draft: false
          prerelease: true
          files: |
            release/${{ env.FILENAME }}.zip
